# Generated by Django 5.2.16 on 2026-07-20 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0001_initial'),
        ('languages_plus', '0004_auto_20171214_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='languages_plus.language'),
        ),
    ]
