# Generated by Django 6.0.2 on 2026-07-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMediations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('audio_file', models.FileField(upload_to='mediation_audios/')),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
