# Generated by Django 6.0.2 on 2026-07-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomediations',
            name='language',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
