# Generated by Django 6.0.2 on 2026-07-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_audiomediations_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomediations',
            name='source_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
