# Generated by Django 5.2.16 on 2026-07-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_audiomediations_source_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomediations',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
